pipeline {
    agent any

    environment {
        DOCKERHUB_USER = 'awasthi25' 
        IMAGE_NAME = 'chatbot'
        DOCKER_CRED_ID = 'docker' 
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage("Docker Build & Push") {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: DOCKER_CRED_ID, usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                        sh "echo $PASS | docker login -u $USER --password-stdin"

                        // CRITICAL FIX: Build inside the folder
                        dir('Chatbot-UI') {
                            sh "docker build -t ${IMAGE_NAME} ."
                        }

                        sh "docker tag ${IMAGE_NAME} ${DOCKERHUB_USER}/${IMAGE_NAME}:latest"
                        sh "docker push ${DOCKERHUB_USER}/${IMAGE_NAME}:latest"
                    }
                }
            }
        }

        stage("Cleanup Old Container") {
            steps {
                sh "docker stop chatbot || true"
                sh "docker rm chatbot || true"
            }
        }

        stage('Deploy to Container (Test)') {
            steps {
                sh "docker run -d --name chatbot -p 3000:3000 ${DOCKERHUB_USER}/${IMAGE_NAME}:latest"
            }
        }
    }
}