pipeline {
    agent any
    
    environment {
        // REPLACE THIS WITH YOUR DOCKER HUB USERNAME
        DOCKERHUB_USER = 'awasthi25' 
        IMAGE_NAME = 'chatbot'
    }
    
    stages {
        stage('Checkout') {
            steps {
                // This automatically pulls the code from your GitHub branch
                checkout scm
            }
        }
        
        stage("Docker Build & Push") {
            steps {
                script {
                    // Uses the 'docker' credentials we created in Jenkins earlier
                    withDockerRegistry(credentialsId: 'docker', toolName: 'docker') {   
                       sh "docker build -t ${IMAGE_NAME} ."
                       sh "docker tag ${IMAGE_NAME} ${DOCKERHUB_USER}/${IMAGE_NAME}:latest"
                       sh "docker push ${DOCKERHUB_USER}/${IMAGE_NAME}:latest"
                    }
                }
            }
        }
        
        stage("Cleanup Old Container") {
            steps {
                // Stop and remove any existing container named 'chatbot' so we can deploy the new one
                sh "docker stop chatbot || true"
                sh "docker rm chatbot || true"
            }
        }

        stage('Deploy to Container (Test)') {
            steps {
                // Run the app on Port 3000 of the Jenkins server
                sh "docker run -d --name chatbot -p 3000:3000 ${DOCKERHUB_USER}/${IMAGE_NAME}:latest"
            }
        }
    }
}